name: 'pre_setup'
description: 'This is the pre setup'
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      id: init
      run: terraform init -input=false -backend-config=environment/dev/gcs-bucket.tfvars
      continue-on-error: false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: true